### ISSUE TITLE
Misc needed fixes

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#367]
- [x] Error in last step of confirming payment receive (e.g. payment sent twice) causes funded multisig wallets to be deleted: TradeManager: Maker error during trade initialization (because ErrorMessageHandler never unregistered)
- [x] It will try to start a local node if last node was local and now one isn't running <-- because `[localhost](http://localhost/)` is authenticated, our check to see if the default local node is running is failing, when it should consider credentials it already has
- [x] Protocol timeout during sign offer does not unreserve and cancel offer post, ack from arbitrator posts offer after timeout
- [x] Protocol timeout during trade initialization causes legacy ui to freeze
- [x] Automatically unreserve key images which aren't part of a known, open offer
- [x] Change version to v0.0.1
- [x] Remove "Fee rate: " from btc
- [x] Edit message of confirmed trade that suggest to contact the bisq community
- [x] Reset arbitrator and seednode

**Comment by erciccione** [comment]
Part of the list above resolved by #368

**Comment by erciccione** [comment]
All except last point: #370

**Comment by erciccione** [comment]
Completed
