### ISSUE TITLE
Minor UI issues 

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno#377]
These are minor UI issues, but that need to be resolved as soon as possible. Any help with these would be greatly appreciated:

- https://github.com/haveno-dex/haveno/issues/426
- https://github.com/haveno-dex/haveno/issues/409
- [x] #431
- [x] #478
- [x] #479 
- [x] #453
- [x] Send fund to self is not registered as used address in receive funds?
- [x] Unconfirmed transactions not appearing in transactions list
- [x] #432
- [x] After arbitration is requested, the app redirects the user to the "mediation" page. Should be "legacy arbitration" instead
- [x] Price indicator sometimes disappears after saving a new account
- [x] Missing confirmation indicator next to tx hashes, sometimes gets stuck or lags behind confirmations
- [x] When creating offer, "Funds needed" says 17.26502975 XMR `null`

**Comment by woodser** [comment]
All issues resolved
